### ISSUE TITLE
Login and Ordering integration

### ISSUE THREAD

**Issue by cloudybyte** [philippd1/gymhmensa#11]
Ich versuch grad ne login integration zu schreiben, aber aspx und MensaMax hassen mich und ich bekomm die ganze Zeit Sitzungsfehler... Hat wer ne idee, woran das liegen könnte?
Integration würde ich natürlich als pullreq submitten😉

**Comment by philippd1** [comment]
Ich kann gerne mal reinschauen, schick den Code mal rüber 😉
Am Besten auch noch Test-Daten zum Login wenn du da was hast?

**Comment by cloudybyte** [comment]
Testdaten zum Login sind halt ein bisschen dumm, weil ich nicht so Lust hab, Login Daten ins internet zu stellen... Sowas ist meistens ne schlechte Idee. Und code steht noch nicht, ich mach grad alles manuell, hat ja letztes mal dann am Ende mit Postman doch geklappt... Kann ich aber gerne schnell machen und hochladen

**Comment by cloudybyte** [comment]
Müsste ja aber auf allen backends gleich funktionieren, also müsstest du ja deine nehmen können...

**Comment by philippd1** [comment]
Ja, einen groben Anhaltspunkt brauche ich natürlich schon 😁
Habe selber keinen Login und weiß daher auch garnicht, wie die Bestellung etc. abläuft 😅

**Comment by cloudybyte** [comment]
Wie bestellt ihr dann das Essen?
Nur vor Ort und Analog?

**Comment by philippd1** [comment]
Gar nicht 🤷‍♂️
Keine Ahnung, sorry!
@Niggl1999 ist schon 2 Jahre nicht mehr an der Schule, bei mir ist es mittlerweile auch 1 Jahr 🤣

Das Projekt hier habe ich damals im Rahmen meines W-Sem. ins Leben gerufen - für die Daten an sich.

Die Integration für Login + Bestellen fände ich natürlich toll, deswegen helfe ich auch gerne mit und führe das hier weiter :)

**Comment by philippd1** [comment]
Ich nehme an, für Login Info etc. hast/ willst du die App reverse-engineeren? @cloudybyte 🤔

**Comment by cloudybyte** [comment]
Also, wenn man sich einloggt, bekommt man nen Token im Browser als Cookie gespeichert, der dann bei den Bestellungen einfach mit übergeben wird. Bestellungen sind einfach ne req mit ein paar query params. Und ich möchte das reversen, weil wir quasi so ne Art Schul Hub bauen, auf der man eben auch Mensa-Bestellungen machen können soll... d.h. der Server wird im Grunde genommen wie ein Proxy funktionieren, der in ner Redis DB die tokens für ne stunde aufbewahrt. Dasselbe machen wir dann auch nochmal fürs Elternportal. Und dann kommen halt noch so Sachen wie Push Notifications auf Mobile etc dazu.

**Comment by philippd1** [comment]
Ja, hört sich ja soweit logisch an.
Aber ohne konkretes URL-Beispiel / Code beispiel kann ich dir nicht helfen, den Fehler zu finden 😁😉

**Comment by Niggl1999** [comment]
Hey @cloudybyte ich unterstütze genauso wie @philippd1 gerne, aber dafür bräuchten wir ein Codebeispiel.
Die Zugangsdaten zum Testen musst du auch nicht öffentlich ins Netz stellen, aber irgendwelche Zugangsdaten brauchen mindestens alle, die helfen sollen (das geht ja auch per Mail oder so).

Das Thema Token zwischenspeichern klingt interessant: Willst du damit die Login-Tokens deiner Nutzer zwischenspeichern?

**Comment by cloudybyte** [comment]
Genau, ich will die tokens in nem redis cache speichern... Relativ easy und sicher, weil der cache von außerhalb des docker-compose netzwerks nicht erreichbar ist. Ich weiß nicht, ob ihr redis kennt, aber das hat so ne schöne expire funktion, mit der sich die Tokens grob gesagt nach ner stunde selber löschen. Dann kann man einfach Testen, ob noch ein Token gecached ist, und sonst nen neuen per login anfordern.

**Comment by philippd1** [comment]
Was du mit deiner internen Technik machst ist mir/uns (ganz ehrlich gesagt) ja egal.
Wenn man mit der Login-/Bestell-Geschichte irgendwo helfen soll (deswegen ja eigentlich der Issue?) dann brauche ich halt mal ein paar Requests (CURL/Postman/Insomnia, mir egal) + zugehörige responses von dir.
Dabei gibst du ja keine deiner Daten preis 🤷‍♂️ Ansonsten bräuchte ich wie gesagt einen Account - habe ich nicht.

**Comment by cloudybyte** [comment]
Habt ihr irgendwie nen discord oder so? Das wäre bequemer, und dann könnte ich die creds per dm schicken...

**Comment by philippd1** [comment]
Klar, kannst mich unter "philippd#5131" adden

**Comment by Niggl1999** [comment]
> Habt ihr irgendwie nen discord oder so? Das wäre bequemer, und dann könnte ich die creds per dm schicken...

Niggl#4162

**Comment by philippd1** [comment]
weiß nicht, ob hier noch was passiert? 🤔 (@cloudybyte)
Ich mach' den issue mal zu.

**Comment by cloudybyte** [comment]
Naja, ich habe nichtmehr dran weitergearbeitet, weil wir noch keinen Zugriff aufs Elternportal haben, und ich alles auf einmal machen wollte... Außerdem wollte ich ne reimplementation in Rust machen. Komme damit iwie besser klar. Hab auch schon angefangen, aber irgendwie liegt das Projekt grade auf Eis.
