### ISSUE TITLE
Offizielle Mensamax API verfügbar

### ISSUE THREAD

**Issue by leubeem** [philippd1/gymhmensa#15]
Hey Philipp,

Ich sehe, ihr habt viel Zeit und Arbeit in den Code gesteckt! Ich war selber gerade dabei, den Speiseplan zu reverse-engineeren.

Glücklicherweiße hat mich eine Bekannte aber darauf gebracht, dass es inzwischen eine offizielle Mensamax Schnittstelle gibt, mit der man einige Funktionen machen kann. Hier der Link; https://docs.mensamax.de/api/#mensamax-api

Das nur für euch zur Info, schade natürlich, wenn euer kompletter Code dann nicht mehr nötig ist :disappointed: 

Grüße,
Emanuel

**Comment by fuerst** [comment]
Die "Offizielle Mensamax API" macht den Anschein, als wäre sie für Betreiber einer Einrichtung gebaut. Für einzelne Kunden relevante Funktionen wie Bestellen/Stornieren sind hier jedenfalls nicht verfügbar.

**Comment by philippdormann** [comment]
Bestellen, Stornieren etc. geht auf jeden Fall über die GraphQL API (https://m.mensamax.de/graphql/auth/login , die URL zum GraphQL Schema kenne ich leider nicht) - diese wird von der "App" verwendet.

**Comment by fuerst** [comment]
Cool, danke für den Tipp! Das Schema gibt es hier:
`curl 'https://m.mensamax.de/graphql/' -H 'Content-Type: application/json' -H 'Accept: application/json' --compressed --data-binary '{"query":"{\n\t__schema{\n queryType {\n fields{\n name\n }\n }\n }\n}"}'`
