### ISSUE TITLE
How does this work? / Why doesn't it work?

### ISSUE THREAD

**Issue by cloudybyte** [philippd1/gymhmensa#5]
I basically need some sort of API for MensaMax...
I put my `projectname` and `einrichtungsnamen` in the /api/index.js and /server.js but it outputs sth othe than our meals...
There is no error in console, and this is the output of the query:

```json
{
	"titles": ["Mo, 13.07.2020", "Di, 14.07.2020", "Mi, 15.07.2020", "Do, 16.07.2020"],
	"list": [{
		"category": "Mittagsgericht 1",
		"days": [
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"]
		]
	}, {
		"category": "Mittagsgericht 2",
		"days": [
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"]
		]
	}, {
		"category": "Schnitzelsandwich",
		"days": [
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"]
		]
	}, {
		"category": "Nudelbox",
		"days": [
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"]
		]
	}, {
		"category": "Nudelbox XL",
		"days": [
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"],
			["Bemerkung: Mensa geschlossen"]
		]
	}],
	"info": {
		"full": "13.07.2020 - 19.07.2020 (KW29)",
		"start": "13.07.2020",
		"end": "19.07.2020",
		"kw": "29",
		"server_data": {
			"cache-control": "private",
			"content-type": "text/html; charset=utf-8",
			"server": "Microsoft-IIS/10.0",
			"x-aspnet-version": "4.0.30319",
			"x-powered-by": "ASP.NET",
			"date": "Sun, 12 Jul 2020 01:15:18 GMT",
			"connection": "close",
			"content-length": "23477"
		}
	}
}
```

**Comment by philippd1** [comment]
❗ First of all, please note the GNU AGPLv3 License


As of what I can see/ what you provided, everything works as designed.
What exactly is your issue? 🤷‍♂️🤷‍♂️

**Comment by cloudybyte** [comment]
The problem is, that the meals are probably the meals of your canteen.
At least they are not the meals that are displayed within the json response.
If we would want this to work at our school, what exactly do I have to change?
I noticed even if I change the P: and E: values it still gets me your menus...

```js
var options = {
	followAllRedirects: true,
	method: 'POST',
	url: 'https://mensadigital.de/LOGINPLAN.ASPX',
	qs: { P: 'KEH111', E: 'ggm' },
	headers: { 'content-type': 'multipart/form-data; boundary=---011000010111000001101001' },
	formData: {
		__VIEWSTATE:
			'G0W5d68B7sQw5+/Q3SXg4OK2k1Tj0FOKG65lU7PQ2OFbtyRUiMicA/M7mVzMyg3315D2xsJw9iECgEYY/fiSRvFwKIde0dUT05/a/saXN4yRgmFS5c3TTgCEhMUd8pejthsVoQYxDhwYyEz4ArewBw==',
		__VIEWSTATEGENERATOR: 'D5B5CA0F',
		btnLogin: ''
	}
};
```

**Comment by philippd1** [comment]
well yes, obviously...🤯
the project calls https://mensadigital.de/LOGINPLAN.ASPX with the given parameters.

so in your case, that would be https://mensadigital.de/LOGINPLAN.ASPX?P=KEH111&E=ggm which returns the following:
![image](https://user-images.githubusercontent.com/17651032/87245229-0b063d80-c444-11ea-9019-f11994649a03.png)

so:
the problem is 100% on your side because you're passing invalid parameters.
Please check again.

**Comment by philippd1** [comment]
@cloudybyte ich nochmal: Ich schreib das hier jetzt mal auf Deutsch, später + in der Doku dann noch Englisch hinterher 😁

---

> Am Anfang noch ein ganz kurzer, genereller Hinweis: Ich persönlich finde, dass es sich gehört, sich beim 1. Kontakt einmal kurzz vorzustellen (+ zu bedanken) - direkt ein "lmao" in einen GitHub Issue hauen kommt nicht so gut an 😉

---

Nach meinem bisherigen Wissensstand gab es die Seiten mensamax.de und mensadigital.de . Ich habe gerade mal ein wenig die Seite deiner Schule erkunded und bin hier auf mensapoint.de gestoßen.

Scheint also, als hätte der Hersteller ("MensaMax GmbH"/ "Breustedt") einfach sehr "interessantes" Branding.

Ich habe soeben mal noch ein bisschen getestet, hier meine Ergebnisse:
Deine Schule funktioniert mit dem Link https://mensapoint.de/LOGINPLAN.ASPX?P=KEH111&E=ggm
Dein Code müsste also so aussehen, damit's funktioniert (untested):
```
var options = {
	followAllRedirects: true,
	method: 'POST',
	url: 'https://mensapoint.de/LOGINPLAN.ASPX',
	qs: { P: 'KEH111', E: 'ggm' },
	headers: { 'content-type': 'multipart/form-data; boundary=---011000010111000001101001' },
	formData: {
		__VIEWSTATE:
			'G0W5d68B7sQw5+/Q3SXg4OK2k1Tj0FOKG65lU7PQ2OFbtyRUiMicA/M7mVzMyg3315D2xsJw9iECgEYY/fiSRvFwKIde0dUT05/a/saXN4yRgmFS5c3TTgCEhMUd8pejthsVoQYxDhwYyEz4ArewBw==',
		__VIEWSTATEGENERATOR: 'D5B5CA0F',
		btnLogin: ''
	}
};
```

Bei Gelegenheit werde ich die API mal so umbauen, dass alle MensaMax-Endpunkte unterstützt werden.

In diesem Sinne:
Meld' dich doch nochmal 💬
❗ Denk' bitte an die Lizenz.

Viel Spaß beim Entwickeln,
Philipp

**Comment by philippd1** [comment]
`mensaonline.de` ist noch eine weitere Domain 🤣

**Comment by philippd1** [comment]
`mensaservice.de` ist noch eine weitere Domain.

Keine Ahnung, wer sich das ausgedacht hat oder was der Hintergedanke ist...

**Comment by cloudybyte** [comment]
naja, das mit den ganzen domains hatte ich schon rausgefunden, dachte nur, dass die alle auf das selbe backend laufen, und nur als alias funktionieren sollen... Die sache is nur, wenn ich `https://mensapoint.de/mensamax/Wochenplan/WochenplanExtern/WochenPlanExternForm.aspx` mit nem Browser aufruf, dann komm ich auf die seite, aber sobald ich ne req über zB postman etc mach, gibts nen error, dass die session abgelaufen ist... Wo hast du die Viewstates und ViewstateGenerators her? Vll ist ja das der Schüssel hinter dem ganzen

**Comment by philippd1** [comment]
*grr, na dann sag + teste das doch gleich mit der URL? 🤷‍♂️

Zur Funktion selbst:
genau dafür gibt's in der README doch den Abschnitt `🛠️ how this works` 🙄
Einige der relevanten Quellen findest du in diesem Repo: https://github.com/philippd1/gymhmensa-intercept

Genau, über Postman/ jedes beliebige HTTP-Request Tool geht das nicht.
Deswegen gibt's das Repo hier ja überhaupt 😁TLDR: du musst immer allen redirects folgen + zwischendrin das ASPX / .NET viewstate rausziehen. 👨‍💻

Ich kann später mal testen, gerade habe ich eher wenig Zeit.

Wie eilig ist es denn? Hast du ein Schulprojekt oder was?

**Comment by cloudybyte** [comment]
nene so eilig ist das nicht, wir versuchen nur quasi so nen "Schulhub" zu coden, zu dem man 1 mal zugangsdaten bekommt, und der einem Zugriff auf alle Dienste bietet... Dazu gehört eben auch  Mensa Essen bestellen, und dafür brauchen wir quasi nen backend server, der alle connections handelt, und der eben auch mensamax pläne läd und bestellreq macht... Und nachdem das .aspx is, und ich absolut keine Lust hatte das zu reversen hab ich gegooglt und bin dann auf das hier gekommen...

**Comment by cloudybyte** [comment]
ok nvm ich habs jetz hinbekommen... Konnte die Viewstates doch abfangen...
Ich werd den ganzen Spaß jetz in Golang umsetzen und die noch die bestellfunktion reversen.
Wenn euch das ergebnis dann interessiert, dann schick ich euch den Link zu dem Repo dann :)

**Comment by cloudybyte** [comment]
Aber danke für die Arbeit

**Comment by philippd1** [comment]
Super, das freut mich. Viel Erfolg!
Sehr gerne, würde mich interessieren - bin gespannt 👍

**Comment by alex-voigt** [comment]
> ok nvm ich habs jetz hinbekommen... Konnte die Viewstates doch abfangen...
> Ich werd den ganzen Spaß jetz in Golang umsetzen und die noch die bestellfunktion reversen.
> Wenn euch das ergebnis dann interessiert, dann schick ich euch den Link zu dem Repo dann :)

Das hört sich sehr cool an. Hast du schon Ergebnisse @cloudybyte ?

**Comment by cloudybyte** [comment]
lmao das ist ein halbes jahr her, go hab ich zugunsten rust sein gelassen und das projekt is auch iwie dead

**Comment by cloudybyte** [comment]
aber ich hab grad eh nix richtiges zu tun, also könnte ichs schon probieren

**Comment by alex-voigt** [comment]
Akuten Bedarf habe ich glücklicherweise nicht, aber ich hatte zumindest die Hoffnung mir das Reverse Engineering zu sparen... 😆  Jetzt werde ich die Tage einfach selbst mal reinschauen.

**Comment by philippdormann** [comment]
Hey
interessant, den Issue nach über einem Jahr mal wieder zu sehen 🤣
Das npm package, welches ich hier vor 2 Monaten veröffentlicht habe funktioniert - ist in Production für einen Kunden.

Oder hast du andere Erfahrungen gemacht? @alex-voigt

**Comment by alex-voigt** [comment]
Eigentlich möchte ich Essensbestellungen für mehrere Accounts vereinfachen und bin über Google direkt auf das Repo hier gestoßen. Bis jetzt ist es auch nur eine Idee. ;-)

**Comment by cloudybyte** [comment]
naja nodejs für backend ist auch nur so semigeil

**Comment by alex-voigt** [comment]
> naja nodejs für backend ist auch nur so semigeil

Mir ging es primär um den Aufbau der API Calls ohne mir alles selbst Ableiten zu müssen. Deswegen auch meine ursprüngliche Frage bzgl. der von dir angekündigten "golang" lib mit Bestellungen  ;-)

**Comment by cloudybyte** [comment]
naja ich hab absolut keine lust auf go kann aber gern mal ne rust crate demnächst dafür schreiben. soo komplex ist das ja nicht

**Comment by philippdormann** [comment]
Mit Go/ Rust kann ich euch hier auch nicht helfen, dafür ist das Projekt nicht da :)

Bestellungen aufgeben und mehr ist komplizierter, schaut euch aber mal die (inoffizielle, private) GraphQL API von MensaMax an. Damit geht das.
