### ISSUE TITLE
Liste an Organisationen?

### ISSUE THREAD

**Issue by philippd1** [philippd1/gymhmensa#7]
@cloudybyte hat mich irgendwie auf die Idee gebracht durch issue #5 :

Bei der Recherche ist aufgefallen, dass MensaMax/Mensapoint/Mensadigital/Mensaservice/Mensaonline teilweise Speisepläne rankt 🤣 - siehe Screenshot (lmao)
![image](https://user-images.githubusercontent.com/17651032/87245859-65ee6380-c449-11ea-9216-4ba2a0685d86.png)

Hier ist folgende URL rausgefallen: https://mensapoint.de/LOGINPLAN.ASPX?P=LL124&E=FWS

Vielleicht möchte ja "jemand"™ mal eine Liste an Insitutionen/ Projekt-IDs machen?

**Comment by philippd1** [comment]
## bekannte Links zu mensaditigal.de (gefunden auf https://www.schulhaus-online.de/mensamax.html)

Link | Institut
-|-
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=dts | "Dr.-Theo-Schöller-Mittelschule in Nürnberg"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=DSK | "Dreiberg Schule Knetzgau"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=ghr | "Georg-Hartmann-Realschule Forchheim"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=hoch | "Gymnasium Höchstadt a.d.Aisch"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=herz | "Gymnasium Herzogenaurach"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=mscadolzburg | "Mittelschule Cadolzburg"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=frid | "Gymnasium Fridericianum"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=msf | "Grund und Mittelschule Feucht"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=feu | "Realschule Feucht"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=SLM | "Mittelschule St. Leonhard Nürnberg"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=gpa | "Georg-Paul-Amberger Grundschule"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=msf | "Kinderhort St. Jakob in Feucht "
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=Schulhaus | "Evangelisches Montessori Kinderhaus Röttenbach"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=ggo | "Grundschule Großgründlach"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=sjw | "St. Josef Kinderhaus"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=drb | "Dientzenhofer Realschule in Brannenburg"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=gsr | "Graf-Stauffenberg-Realschule in Bamberg"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=lurf | "Leopold-Ullstein-Realschule Fürth"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=hlg | "Helene-Lange-Gymnasium in Fürth"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=kat | "Grund- und Mittelschule Nürnberg-Katzwang"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=sfh | "St. Franziskus Kinderhaus"
https://mensadigital.de/LOGINPLAN.ASPX?P=FO111&E=GSHerzogenaurach | "Grundschule Herzogenaurach"

**Comment by Niggl1999** [comment]
Ich würde Vorschlagen wir ziehen die Liste ins Wiki um.
Ich kümmere mich darum.
