### ISSUE TITLE
List of all MensaMax Domains

### ISSUE THREAD

**Issue by cloudybyte** [philippd1/gymhmensa#8]
# !Important! All these domains seem to point to different backends! You cannot use them interchangably!

Main Website: mensamax.de

- `mensadigital.de`
- `mensawelten.de`
- `mensaonline.de`
- `mensaservice.de`

**Comment by philippd1** [comment]
kommt dann in die README zu den einzelnen URLs...

**Comment by cloudybyte** [comment]
Oke

**Comment by cloudybyte** [comment]
mensahome.de gibts btw auch noch

**Comment by philippd1** [comment]
schon gefunden :)
danke, aber brauchst dir hier keine Mühe mehr machen 😉
Bin mittlerweile bei 11 Domains 🤣🤷‍♂️

**Comment by cloudybyte** [comment]
haha wow...
Hast mensaweb schon?
Hab die durch zufall grad gefunden?

**Comment by philippd1** [comment]
Ja, ich glaube tatsächlich ich hab' alle 😉
Ich bin für heute mit der Hauptarbeit durch.
Jetzt bastel gerade an einer neuen Version, damit die API hier mit allen funktioniert 👍

**Comment by philippd1** [comment]
Hey @cloudybyte 👋
also wie du siehst habe ich mal noch ein bisschen weiter gebaut :)
Das Projekt nimmt jetzt alle MensaMax-URLs an, alle Projekte sind einheitlich hinterlegt und müssen manuell getestet werden.
Falls dich die Liste an Domains interessiert: `/mensa-urls.txt`
